import {
  internalError,
  invalidInput,
  json,
  notFound,
  searchParamsObject,
  unauthorized,
} from "@/lib/api/response"
import { requireSessionForApi } from "@/lib/auth/guard"
import { toRunView, type RunView } from "@/lib/db/views"
import { loadRunGaps, type RunGap } from "@/lib/runs/gaps"
import { runIdParamSchema, runQuerySchema } from "@/lib/runs/input"
import { findOwnedRun } from "@/lib/runs/state"

/**
 * `GET /api/runs/[runId]` — one run's state, plus its gap list (Requirements 36.7,
 * 36.10, 36.11, 40.4, 7.7).
 *
 * This is the endpoint a reconnecting client rebuilds from. Requirement 40.4 says
 * the displayed state is reconstructed from the row and the stored gap list, and
 * that the client requests **no event replay** from the runtime — so this handler is
 * the replacement for a replay, and it returns exactly those two things.
 *
 * `export const runtime = "nodejs"` because the read opens a Postgres connection
 * and the gap list reaches S3, neither of which runs on the edge runtime.
 *
 * ## Terminal state comes from the row, not only from events
 *
 * Requirement 36.7, and it is the reason this route exists alongside the stream:
 * `TIMEOUT` is written by the reaper **with no event to carry it**, because by then
 * the run's container may already be gone. A client that read terminal state only
 * from the event stream would show a timed-out run as still collecting, forever. So
 * `status`, `errorCode` and `errorMessage` are all on {@link RunView}, and the row
 * is the record.
 *
 * ## The gap list costs an S3 read, on terminal rows only
 *
 * `loadRunGaps` returns `[]` for a non-terminal run **without making a request**, so
 * a client polling this route while a run collects pays one Postgres read per poll
 * and nothing else. It also never throws: a completed run whose snapshot object
 * cannot be read is still a completed run, and failing this response because a gap
 * list was unavailable would turn a cosmetic problem into an apparent run failure.
 */
export const runtime = "nodejs"

/**
 * The awaited-params shape Next 16 requires for a dynamic route handler: `params`
 * is a **Promise**, and synchronous access was removed
 * (`02-guides/upgrading/version-16.md`).
 *
 * Typed structurally rather than with the generated `RouteContext<'/api/runs/[runId]'>`
 * global, matching the decision the subscriptions secret route makes: `.next/types`
 * is generated by `next typegen` and git-ignored, so a checkout that has not built
 * yet would fail `pnpm typecheck` on a name that does not exist. The shape is
 * identical to the one the generated helper declares.
 */
type RunRouteContext = Readonly<{ params: Promise<{ runId: string }> }>

/** The success body. */
type RunResponseBody = {
  readonly run: RunView
  /** Empty until the run is terminal — see {@link loadRunGaps}. */
  readonly gaps: readonly RunGap[]
}

export async function GET(
  request: Request,
  context: RunRouteContext
): Promise<Response> {
  const user = await requireSessionForApi()
  if (user === null) return unauthorized()

  // Requirement 7.7 — the path parameter is input, parsed with a named schema like
  // any body. `await` because Next 16 removed synchronous `params`.
  const params = runIdParamSchema.safeParse(await context.params)
  if (!params.success) return invalidInput(params.error)

  const query = runQuerySchema.safeParse(searchParamsObject(request.url))
  if (!query.success) return invalidInput(query.error)

  try {
    // Requirements 36.10, 36.11 — scoped by `user_id` inside the statement, so
    // another user's run matches no row and no field of it is read, let alone
    // returned. Resolved as not found rather than forbidden: a "forbidden" answer
    // would confirm the run exists, and its `status` and `error_code` are facts
    // about somebody else's customer.
    const run = await findOwnedRun(user.id, params.data.runId)
    if (run === undefined) return notFound()

    const gaps = await loadRunGaps(run)

    return json(200, {
      run: toRunView(run),
      gaps,
    } satisfies RunResponseBody)
  } catch (thrown) {
    console.error(
      `[api/runs/[runId]] GET failed: ` +
        `${thrown instanceof Error ? `${thrown.name}: ${thrown.message}` : typeof thrown}`
    )

    return internalError()
  }
}
