import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeftIcon } from "@phosphor-icons/react/ssr"

import { RunProgress } from "@/components/reports/run-progress"
import { SnapshotProvenance } from "@/components/reports/snapshot-provenance"
import { SecretExpiryBanner } from "@/components/subscriptions/secret-expiry-banner"
import { requireSession } from "@/lib/auth/guard"
import { toRunView, UNRESOLVED_RUN_VIEW_EXTRAS } from "@/lib/db/views"
import { loadRunGaps, loadRunProvenance } from "@/lib/runs/gaps"
import { periodLine } from "@/lib/runs/presentation"
import { findOwnedRun } from "@/lib/runs/state"
import { resolveSubscriptionState } from "@/lib/subscriptions/state"
import { getConnectedSubscription } from "@/lib/subscriptions/store"

/**
 * `/reports/[runId]` — one run's detail (Requirements 36.7, 36.10, 36.11, 40.4).
 *
 * A **server** component with exactly one client leaf below it: `RunProgress`, which owns
 * the stream. Everything the first paint needs is read here and passed down, so the page
 * is correct before any connection opens — and a terminal run opens no connection at all.
 *
 * ## Terminal state is read from the row
 *
 * Requirement 36.7, and this page is where it bites hardest. `TIMEOUT` is written by the
 * reaper when the run's container may already be gone, so it arrives with **no event to
 * carry it** — a page that rendered only what the stream said would show a timed-out run
 * as still collecting, indefinitely. The row is read here and handed to the client leaf as
 * `initialRun`, so the failure notice renders on a page that received no events.
 *
 * ## Two S3 reads, both on a terminal row only, and neither able to fail the page
 *
 * `loadRunGaps` and `loadRunProvenance` each return an empty result for a non-terminal run
 * **without making a request**, and both swallow a read failure. A completed run whose
 * snapshot object cannot be read is still a completed run; failing this page because a gap
 * list was unavailable would turn a cosmetic problem into an apparent run failure.
 *
 * ## The expiry banner appears here too
 *
 * Requirement 13.2 puts the approaching-expiry warning on the run screens for that
 * subscription, not only on the subscriptions screen — because this is where a consultant
 * looks when they are about to request another one. It renders in **mist neutrals**: an
 * approaching expiry is information, and `--destructive` is reserved for a run that
 * failed.
 */

/**
 * The awaited-params shape Next 16 requires for a dynamic page: `params` is a
 * **Promise**, and synchronous access was removed
 * (`02-guides/upgrading/version-16.md`).
 *
 * Typed structurally rather than with the generated `PageProps<'/reports/[runId]'>`
 * global, matching the decision the auth pages make: `.next/types` is generated by
 * `next typegen` and git-ignored, so a checkout that has not built yet would fail
 * `pnpm typecheck` on a name that does not exist.
 */
type RunPageProps = Readonly<{ params: Promise<{ runId: string }> }>

export const metadata: Metadata = {
  title: "Report run",
  description:
    "One report run: its activity, its snapshot provenance and its recorded " +
    "collection gaps.",
}

export default async function RunPage({ params }: RunPageProps) {
  const user = await requireSession()

  const { runId } = await params

  // Requirements 36.10, 36.11 — scoped by `user_id` inside the statement, so another
  // user's run matches no row and no field of it is read. `notFound()` rather than a
  // "forbidden" page: confirming the run exists would itself be a fact about somebody
  // else's customer.
  const run = await findOwnedRun(user.id, runId)
  if (run === undefined) notFound()

  // Requirement 37.1's template name, pinned version and verification status
  // are not resolved by this page yet: `run.templateVersionId` is `null`
  // until task 13.1, and no run reaches `verifying` until task 11.5. See
  // `UNRESOLVED_RUN_VIEW_EXTRAS`'s docstring.
  const view = toRunView(run, UNRESOLVED_RUN_VIEW_EXTRAS)

  const [gaps, provenance] = await Promise.all([
    loadRunGaps(run),
    loadRunProvenance(run),
  ])

  // The subscription may have been removed since the run — `report_runs` rows are audit
  // artifacts and outlive the connection they targeted — so this read is allowed to come
  // back empty and the page still renders.
  const subscription = await getConnectedSubscription(
    user.id,
    run.connectedSubscriptionId
  ).catch(() => null)

  const subscriptionLabel =
    subscription === null
      ? "Subscription removed"
      : `${subscription.displayName} — ${subscription.maskedSubscriptionId}`

  const subscriptionState =
    subscription === null
      ? null
      : resolveSubscriptionState(subscription, new Date())

  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-8">
      <div className="flex flex-col gap-2">
        <Link
          href="/reports"
          className="flex w-fit items-center gap-1.5 rounded-lg text-sm text-muted-foreground outline-none hover:text-foreground focus-visible:ring-3 focus-visible:ring-ring/30"
        >
          <ArrowLeftIcon aria-hidden="true" className="size-4" />
          All reports
        </Link>

        <h1 className="font-heading text-xl font-medium tracking-tight">
          {subscriptionLabel}
        </h1>

        {/* The zone travels with the dates, on every surface that names a period. */}
        <p className="font-mono text-sm text-muted-foreground tabular-nums">
          {periodLine(view)}
        </p>
      </div>

      {/*
        Requirement 13.2 — the warning follows the subscription onto the run screens.
        Only the `expiring` state renders a banner here; `expired` and `disabled` are
        surfaced on the subscriptions screen with their rotate action, and a run against
        such a subscription fails with `AUTH_EXPIRED`, which the failure notice explains.
      */}
      {subscriptionState?.kind === "expiring" ? (
        <SecretExpiryBanner state={subscriptionState} />
      ) : null}

      <RunProgress
        initialRun={view}
        initialGaps={gaps}
        subscriptionLabel={subscriptionLabel}
      />

      {run.status === "completed" ? (
        <section className="flex flex-col gap-3">
          <h2 className="font-heading text-sm font-medium tracking-tight">
            Snapshot provenance
          </h2>

          <p className="max-w-prose text-sm text-muted-foreground">
            The snapshot is immutable and content-addressed: its id <em>is</em>{" "}
            the hash of its bytes, so a figure quoted from this report can be
            traced to exactly the data it came from.
          </p>

          <SnapshotProvenance run={view} provenance={provenance} />
        </section>
      ) : null}
    </div>
  )
}
