import {
  deleteTemplate,
  publishTemplateVersion,
  renameTemplate,
  saveDraft,
  TemplateInvalidError,
} from "@/lib/actions/templates"
import {
  conflict,
  internalError,
  invalidInput,
  json,
  malformedBody,
  notFound,
  readJsonBody,
  unauthorized,
  type ApiErrorBody,
} from "@/lib/api/response"
import { requireSessionForApi } from "@/lib/auth/guard"
import {
  toTemplateVersionView,
  toTemplateView,
  type TemplateVersionView,
  type TemplateView,
  templateViewCurrentVersion,
} from "@/lib/db/views"
import {
  templateIdParamSchema,
  templatePatchInputSchema,
  templatePublishInputSchema,
} from "@/lib/templates/input"
import {
  getTemplate,
  readLatestVersion,
  TemplateNotFoundError,
  TemplatePinnedByRunError,
  TemplateVersionSequencingError,
} from "@/lib/templates/store"

/**
 * One template: read it, patch it, version it, delete it (Requirements 1.4, 1.5,
 * 9.2, 9.3, 9.5, 9.11, 10.7, 11.4, 7.7).
 *
 * `export const runtime = "nodejs"` because every handler opens a Postgres
 * connection.
 *
 * ## Not found, never forbidden — and the same answer for both
 *
 * Requirement 1.5 requires a template that belongs to somebody else to be
 * **indistinguishable** from one that does not exist. The store enforces it at
 * the statement (`AND user_id = $2` matches no row, so no field is read), and
 * every handler here maps {@link TemplateNotFoundError} to the shared
 * {@link notFound} helper — the same fixed body every other not-found in the app
 * returns, byte for byte. A 403 would confirm the row exists, and its existence
 * is a fact about somebody else's customer.
 *
 * ## `/api/templates/catalog` is a sibling, not a match for `[id]`
 *
 * Next resolves a static segment before a dynamic one, so `GET
 * /api/templates/catalog` reaches `../catalog/route.ts` and never arrives here
 * with `id: "catalog"`. Worth stating because the failure would be quiet: this
 * handler would answer `404` for the catalog, which reads exactly like a
 * signed-out session.
 */
export const runtime = "nodejs"

/**
 * The awaited-params shape Next 16 requires for a dynamic route handler.
 *
 * Typed structurally rather than with the generated
 * `RouteContext<'/api/templates/[id]'>` global, matching every other dynamic
 * route here: `.next/types` is generated by `next typegen` and git-ignored, so a
 * checkout that has not built yet would fail `pnpm typecheck` on a name that
 * does not exist.
 */
type TemplateRouteContext = Readonly<{ params: Promise<{ id: string }> }>

type ReadResponseBody = {
  readonly template: TemplateView
  /**
   * The wizard's in-progress definition, or `null`.
   *
   * The **only** place the draft's own content crosses to the browser.
   * {@link TemplateView} deliberately carries `hasDraft` rather than the draft,
   * so a list of templates is a list of names and digests; this handler is the
   * one a wizard opens, and it is the one that needs the tree.
   */
  readonly draftDefinition: unknown
  /** The highest existing version, or `null` before step 7 has ever completed. */
  readonly currentVersion: TemplateVersionView | null
}

type PatchResponseBody = { readonly template: TemplateView }

type PublishResponseBody = {
  readonly version: TemplateVersionView
  /**
   * `false` when the submitted digest matched the existing highest version and
   * no row was inserted (Requirement 9.5).
   *
   * Surfaced rather than hidden, for the reason `EnqueueResult.deduplicated` is:
   * the two cases have different statuses — `201` for a version that was
   * created, `200` for one that already existed — and a wizard that cannot tell
   * them apart cannot honestly say "saved as version 4" versus "no changes to
   * save".
   */
  readonly created: boolean
}

/** A validation rejection carrying every failing field path (Requirement 2.7). */
function definitionRejected(thrown: TemplateInvalidError): Response {
  return json(400, {
    error: {
      message: thrown.message,
      code: "TEMPLATE_INVALID",
      fields: thrown.issues.map((issue) => ({
        path: issue.path.map(String).join("."),
        message: issue.message,
      })),
    },
  } satisfies ApiErrorBody)
}

/** The one place a thrown store error becomes a status. */
function storeFailure(operation: string, thrown: unknown): Response {
  if (thrown instanceof TemplateNotFoundError) return notFound()

  if (thrown instanceof TemplateInvalidError) return definitionRejected(thrown)

  if (thrown instanceof TemplatePinnedByRunError) {
    // 409 rather than 422: the request is well-formed and the refusal is about
    // the *state* of the resource — reports exist — which is what a conflict is.
    return conflict(thrown.message, "TEMPLATE_PINNED")
  }

  if (thrown instanceof TemplateVersionSequencingError) {
    // Requirement 9.11 — three retries lost the `(template_id, version)` race.
    // A conflict rather than a 500: nothing is broken, the save did not happen,
    // and pressing save again is the correct response.
    return conflict(thrown.message, "VERSION_SEQUENCING")
  }

  // An unexpected throw reaches here, and the response deliberately carries
  // nothing from it (see `internalError`). The LOG is therefore the only record
  // of what actually happened, so it gets the stack: without one, a
  // `TypeError: Cannot convert undefined or null to object` names neither the
  // file nor the field, which is exactly how a v3-publish defect stayed
  // un-diagnosable from the server log alone.
  console.error(
    `[api/report-profiles/[id]] ${operation} failed: ` +
      `${thrown instanceof Error ? `${thrown.name}: ${thrown.message}` : typeof thrown}`,
    thrown instanceof Error ? (thrown.stack ?? "") : thrown
  )

  return internalError()
}

/**
 * The template, its draft and its current version (Requirement 11.6).
 *
 * This is the read the wizard opens with: Requirement 11.6 has reopening a
 * template restore "every persisted value", and the draft column is where those
 * values are. Returning the version alongside is what lets step 7 say whether
 * publishing would create a version or return the existing one.
 */
export async function GET(
  _request: Request,
  context: TemplateRouteContext
): Promise<Response> {
  const user = await requireSessionForApi()
  if (user === null) return unauthorized()

  const params = templateIdParamSchema.safeParse(await context.params)
  if (!params.success) return invalidInput(params.error)

  try {
    const template = await getTemplate(user.id, params.data.id)
    const version = (await readLatestVersion(user.id, params.data.id)) ?? null

    return json(200, {
      template: toTemplateView(
        template,
        version === null ? null : templateViewCurrentVersion(version)
      ),
      draftDefinition: template.draftDefinition,
      currentVersion: version === null ? null : toTemplateVersionView(version),
    } satisfies ReadResponseBody)
  } catch (thrown) {
    return storeFailure("GET", thrown)
  }
}

/**
 * Write the draft, rename, or both — and insert **no** version row
 * (Requirement 11.4).
 *
 * The draft is written unvalidated, and that is the requirement rather than an
 * omission: "a step transition or an explicit save writes the draft and inserts
 * no version row, whether or not step 7 was reached and whether or not the
 * definition yet carries a block". A wizard that could only persist a valid
 * draft would discard the consultant's work every time they left a step
 * mid-edit.
 *
 * The two writes are applied in the order the body names them and each is
 * separately scoped, so a rename to a name the CHECK constraint refuses leaves
 * the draft alone rather than half-applying.
 */
export async function PATCH(
  request: Request,
  context: TemplateRouteContext
): Promise<Response> {
  const user = await requireSessionForApi()
  if (user === null) return unauthorized()

  const params = templateIdParamSchema.safeParse(await context.params)
  if (!params.success) return invalidInput(params.error)

  const body = await readJsonBody(request)
  if (body === undefined) return malformedBody()

  const parsed = templatePatchInputSchema.safeParse(body)
  if (!parsed.success) return invalidInput(parsed.error)

  try {
    let template =
      parsed.data.name === undefined
        ? await getTemplate(user.id, params.data.id)
        : await renameTemplate(user.id, params.data.id, parsed.data.name)

    // `in` rather than `!== undefined`: sending `draftDefinition: null` discards
    // the draft, and omitting the key leaves it alone. The two are different
    // requests and a truthiness check would collapse them.
    if ("draftDefinition" in parsed.data) {
      template = await saveDraft(
        user.id,
        params.data.id,
        parsed.data.draftDefinition
      )
    }

    const version = (await readLatestVersion(user.id, params.data.id)) ?? null

    return json(200, {
      template: toTemplateView(
        template,
        version === null ? null : templateViewCurrentVersion(version)
      ),
    } satisfies PatchResponseBody)
  } catch (thrown) {
    return storeFailure("PATCH", thrown)
  }
}

/**
 * Validate, canonicalize and insert the next version — or return the existing
 * one unchanged (Requirements 9.2, 9.4, 9.5).
 *
 * `created` is decided by comparing the returned version's id against the
 * highest version *before* the call. That is a read the store already performs
 * internally, repeated here rather than returned from it, and the alternative —
 * widening `insertVersion` to report whether it inserted — was rejected because
 * it would put an HTTP status code's concern into the sequencing loop.
 */
export async function POST(
  request: Request,
  context: TemplateRouteContext
): Promise<Response> {
  const user = await requireSessionForApi()
  if (user === null) return unauthorized()

  const params = templateIdParamSchema.safeParse(await context.params)
  if (!params.success) return invalidInput(params.error)

  const body = await readJsonBody(request)
  if (body === undefined) return malformedBody()

  const parsed = templatePublishInputSchema.safeParse(body)
  if (!parsed.success) return invalidInput(parsed.error)

  try {
    const before = await readLatestVersion(user.id, params.data.id)

    const version = await publishTemplateVersion(
      user.id,
      params.data.id,
      parsed.data.definition
    )

    const created = version.id !== before?.id

    return json(created ? 201 : 200, {
      version: toTemplateVersionView(version),
      created,
    } satisfies PublishResponseBody)
  } catch (thrown) {
    return storeFailure("POST", thrown)
  }
}

/**
 * Delete the template and every version no run pinned (Requirements 9.8, 10.7).
 *
 * A template that produced a report cannot be deleted, and the two foreign keys
 * on `template_version_id` are what refuse it rather than a check in this
 * handler — see `lib/templates/store.ts#deleteTemplate`. That refusal reaches the
 * consultant as a `409` naming the reason, because "you have reports from this
 * template" is something they can act on: rename it, or leave it.
 *
 * `204` on success, with no body. A deleted template has no representation to
 * return, and answering `200 {}` would invite a caller to look for one.
 */
export async function DELETE(
  _request: Request,
  context: TemplateRouteContext
): Promise<Response> {
  const user = await requireSessionForApi()
  if (user === null) return unauthorized()

  const params = templateIdParamSchema.safeParse(await context.params)
  if (!params.success) return invalidInput(params.error)

  try {
    await deleteTemplate(user.id, params.data.id)

    return new Response(null, {
      status: 204,
      headers: { "Cache-Control": "no-store" },
    })
  } catch (thrown) {
    return storeFailure("DELETE", thrown)
  }
}
