import {
  internalError,
  invalidInput,
  json,
  notFound,
  searchParamsObject,
  serviceUnavailable,
  unauthorized,
  unprocessable,
} from "@/lib/api/response"
import { requireSessionForApi } from "@/lib/auth/guard"
import { MissingRuntimeConfigError } from "@/lib/aws/agentcore"
import type { SubscriptionStatus } from "@/lib/db/schema"
import {
  inventoryParamsSchema,
  inventoryQuerySchema,
} from "@/lib/subscriptions/input"
import {
  readInventoryCache,
  writeInventoryCache,
  type InventoryDimensions,
} from "@/lib/subscriptions/inventory-cache"
import {
  listInventory,
  type InventoryUnavailableReason,
} from "@/lib/subscriptions/inventory"
import {
  readSubscriptionRowState,
  resolveSubscriptionCredentials,
  SubscriptionNotFoundError,
  SubscriptionSecretUnreadableError,
} from "@/lib/subscriptions/store"

/**
 * `GET /api/subscriptions/[id]/inventory` — the distinct dimensions the wizard's
 * pickers offer (Requirements 9.1, 9.2, 9.3, 9.4, 9.8, 9.9).
 *
 * ## The order is three criteria, and it is the whole design
 *
 * 1. **Ownership.** A `user_id` differing from the signed-in user's resolves as
 *    **not found**, with no Azure query and no field of that row disclosed — and
 *    byte-identical to the answer for an id that exists for no row at all. That
 *    identity is not a nicety: the existence of a connected subscription is itself a
 *    fact about somebody else's customer, so "forbidden" would answer a question the
 *    caller is not entitled to ask. `readSubscriptionRowState`'s `AND user_id`
 *    predicate is what makes it structural rather than a comparison this handler
 *    could forget.
 * 2. **Status.** A `status` other than `active` resolves as unavailable **naming
 *    that status and nothing else**. This is what drives the picker's free-entry
 *    fallback (Requirement 9.6). The alternative — answering with four empty
 *    dimensions — is the failure worth stating plainly: a consultant reads an empty
 *    option list as an empty subscription, and an expired secret is exactly the
 *    condition that produces one.
 * 3. **The cache**, and only then. Consulted after ownership, so a probe cannot
 *    learn from a timing difference whether a row exists; keyed on the row id alone;
 *    invalidated by the `updated_at` this handler has already loaded.
 *
 * A miss invokes the runtime with the `list_inventory` **command** carrying the
 * server-resolved Azure credentials in its `context`. Never a prompt: the pickers
 * need the actual inventory, not a model's account of it, and there is no model in
 * that path to have an account.
 *
 * ## What is bounded, and what is not retried
 *
 * The wait on the runtime is capped at 30 seconds by
 * `lib/subscriptions/inventory.ts`, and an attempt that resolves as unavailable
 * writes **no cache entry** and issues **no automatic retry**. The absence of the
 * retry is deliberate: three pickers on one screen retrying a throttled subscription
 * would turn one rate limit into a queue of them, and the caller with the context to
 * decide whether asking again is worth it is the consultant, not this handler.
 *
 * ## What crosses to the browser
 *
 * Four lists of strings and a `truncated` flag each. No fully qualified resource
 * identifier, no subscription id, no tenant id, no client id — the runtime's query
 * projects the four dimensions and nothing else, so the exclusion is a property of
 * the projection rather than a filter this route applies afterwards. The unavailable
 * answers name a `status` or one of three reasons, and nothing about the row beyond
 * that.
 *
 * `Cache-Control: no-store` on every response, from `lib/api/response.ts`: the body
 * is one customer's inventory, and an intermediary holding it would serve it to the
 * next requester.
 */
export const runtime = "nodejs"

/**
 * The awaited-params shape Next 16 requires for a dynamic route handler: `params` is
 * a **Promise**, and synchronous access was removed
 * (`02-guides/upgrading/version-16.md`).
 *
 * Typed structurally rather than with the generated
 * `RouteContext<'/api/subscriptions/[id]/inventory'>` global, matching its sibling
 * route: `.next/types` is generated by `next typegen` and git-ignored, so a checkout
 * that has not built yet would fail `pnpm typecheck` on a name that does not exist.
 */
type InventoryRouteContext = Readonly<{ params: Promise<{ id: string }> }>

/** The success body. */
type InventoryResponseBody = {
  readonly inventory: InventoryDimensions
  /** Whether this answer came from the cache rather than from a fresh query. */
  readonly cached: boolean
}

/** `422` codes, so the picker can tell the two unavailable shapes apart. */
const STATUS_UNAVAILABLE_CODE = "SUBSCRIPTION_NOT_ACTIVE"
const RUNTIME_UNAVAILABLE_CODE = "INVENTORY_UNAVAILABLE"

/**
 * What a non-`active` status says (Requirement 9.9).
 *
 * Names the status and stops. Not why it holds that status — a `pending` row has an
 * unproven scope and a `disabled` one has a credential Azure refused, and both of
 * those are facts the subscription's own screen states, with the remedy attached. A
 * second telling here would be a second place to keep in step with
 * `lib/subscriptions/state.ts`.
 */
function statusUnavailable(status: SubscriptionStatus): Response {
  return unprocessable(
    `This subscription's status is "${status}", so its inventory was not ` +
      `listed. Enter values directly instead.`,
    STATUS_UNAVAILABLE_CODE
  )
}

/**
 * What a runtime failure says (Requirement 9.8).
 *
 * The reason travels as a field rather than only inside the prose, because the three
 * are not interchangeable and the picker's statement of *why* differs: nothing
 * answered, the answer was no, or the answer never came. The runtime's own code — a
 * `THROTTLED` or an `AUTH_FAILED` — travels too where it named one, since an
 * expired credential has a remedy and a rate limit has a wait.
 */
function runtimeUnavailable(
  reason: InventoryUnavailableReason,
  message: string,
  code: string | undefined
): Response {
  return json(422, {
    error: {
      message,
      code: code ?? RUNTIME_UNAVAILABLE_CODE,
      fields: [{ path: "reason", message: reason }],
    },
  })
}

export async function GET(
  request: Request,
  context: InventoryRouteContext
): Promise<Response> {
  const user = await requireSessionForApi()
  if (user === null) return unauthorized()

  // Requirement 9.3 — both halves of the input parsed with a named schema. `await`
  // because Next 16 removed synchronous `params`.
  const params = inventoryParamsSchema.safeParse(await context.params)
  if (!params.success) return invalidInput(params.error)

  const query = inventoryQuerySchema.safeParse(searchParamsObject(request.url))
  if (!query.success) return invalidInput(query.error)

  const subscriptionRowId = params.data.id

  try {
    // Step 1 — ownership. Scoped by `user_id` in the statement, so another user's id
    // matches no row, reads no field and answers exactly as an absent id does.
    const row = await readSubscriptionRowState(user.id, subscriptionRowId)

    // Step 2 — status, before the cache and before any credential is decrypted.
    if (row.status !== "active") return statusUnavailable(row.status)

    // Step 3 — the cache. One instant for the read and for the write below, so a
    // slow listing is not stored as though it had completed when the request began.
    const now = Date.now()
    const cached = readInventoryCache(subscriptionRowId, row.updatedAt, now)

    if (cached !== undefined) {
      return json(200, {
        inventory: cached,
        cached: true,
      } satisfies InventoryResponseBody)
    }

    // Resolved only on a miss, and decrypted at this instant rather than held
    // anywhere. A cache hit therefore never touches the stored envelope.
    const credentials = await resolveSubscriptionCredentials(
      user.id,
      subscriptionRowId
    )

    const listing = await listInventory({
      actorId: user.id,
      displayName: row.displayName,
      credentials,
    })

    if (!listing.available) {
      // Requirement 9.8 — no cache entry for an attempt that produced no listing,
      // and no retry from here.
      return runtimeUnavailable(listing.reason, listing.message, listing.code)
    }

    // Stored against the `updated_at` observed in step 1. A rotation that landed
    // while the query was running leaves that value behind the row's current one,
    // so the next request misses and lists again — the safe direction of the race.
    writeInventoryCache(
      subscriptionRowId,
      row.updatedAt,
      listing.dimensions,
      Date.now()
    )

    return json(200, {
      inventory: listing.dimensions,
      cached: false,
    } satisfies InventoryResponseBody)
  } catch (thrown) {
    if (thrown instanceof SubscriptionNotFoundError) {
      // Requirements 9.4, 9.8 — not found, never forbidden, and the same answer for
      // an id that is somebody else's as for one that exists for no row.
      return notFound()
    }

    if (thrown instanceof SubscriptionSecretUnreadableError) {
      // Reachable only for an `active` row whose stored envelope no longer decrypts,
      // which is a row that needs rotating. Unavailable rather than a 500: the
      // request is answerable, and the answer is that this subscription cannot be
      // listed until its secret is replaced.
      return unprocessable(thrown.message, "SECRET_UNREADABLE")
    }

    if (thrown instanceof MissingRuntimeConfigError) {
      // Our deployment, not this customer's subscription. `503` and a message that
      // names no variable.
      return serviceUnavailable(
        "The reporting runtime is not configured, so no subscription's " +
          "inventory can be listed.",
        "RUNTIME_UNCONFIGURED"
      )
    }

    // The store redacts what it throws — the operation and the SQLSTATE, nothing
    // else — so this line cannot write a credential or a subscription id into a log.
    console.error(
      `[api/subscriptions/[id]/inventory] GET failed: ` +
        `${thrown instanceof Error ? `${thrown.name}: ${thrown.message}` : typeof thrown}`
    )

    return internalError()
  }
}
