/**
 * The AWS onboarding artifacts — a CloudFormation template and an AWS CLI script that
 * create the read-only role the reporting agent assumes in a customer's account.
 *
 * **Pure, and deliberately not `server-only`**, like `azure-artifacts.ts`: an account id,
 * an external id and our principal in, two strings out. No I/O, no clock, no randomness —
 * the external id is generated by the store when the connector is created, never here and
 * never by the browser.
 *
 * **One source for what is granted.** The actions, the role's path and name and its
 * session length come from `agent/src/reporting_agent/aws/reader_policy.v1.json`, the same
 * file the runtime's preflight simulates. What the customer grants and what the preflight
 * checks cannot drift apart.
 *
 * Written to be **read**: a security reviewer at the customer approves these, so each
 * statement says what it is for, and there is nothing a reviewer has to evaluate in their
 * head.
 */

import readerPolicy from "../../../agent/src/reporting_agent/aws/reader_policy.v1.json"

type Statement = {
  readonly sid: string
  readonly purpose: string
  readonly actions: readonly string[]
  readonly self_only?: boolean
}

const POLICY = readerPolicy as {
  readonly role_path: string
  readonly role_name: string
  readonly policy_name: string
  readonly max_session_seconds: number
  readonly statements: readonly Statement[]
}

export const AWS_ROLE_PATH = POLICY.role_path
export const AWS_ROLE_NAME = POLICY.role_name
export const AWS_POLICY_NAME = POLICY.policy_name
export const AWS_STACK_NAME = "reporting-agent-reader"

/** Every action the role grants, in the policy file's order. */
export const AWS_REQUIRED_ACTIONS: readonly string[] = POLICY.statements.flatMap(
  (statement) => statement.actions
)

const ACCOUNT_ID = /^\d{12}$/
const EXTERNAL_ID = /^rpt-[0-9a-f]{32}$/
const PRINCIPAL_ARN = /^arn:aws:iam::\d{12}:role\/[\w+=,.@/-]+$/

export function isAwsAccountId(value: string): boolean {
  return ACCOUNT_ID.test(value)
}

export function isExternalId(value: string): boolean {
  return EXTERNAL_ID.test(value)
}

export function isPrincipalArn(value: string): boolean {
  return PRINCIPAL_ARN.test(value)
}

/** The only role ARN a connector may use: fixed path and name, in the customer's account. */
export function readerRoleArn(accountId: string): string {
  return `arn:aws:iam::${accountId}:role${AWS_ROLE_PATH}${AWS_ROLE_NAME}`
}

export type AwsArtifactInput = {
  /** The customer's 12-digit account id. */
  readonly accountId: string
  /** `rpt-` and 32 hex characters, issued for this connector. */
  readonly externalId: string
  /** The reporting agent's runtime role, which the customer's role trusts. */
  readonly principalArn: string
}

function checked(input: AwsArtifactInput): AwsArtifactInput {
  if (!isAwsAccountId(input.accountId)) throw new Error("The AWS account id must be 12 digits.")
  if (!isExternalId(input.externalId)) throw new Error("The external id is not one this service issued.")
  if (!isPrincipalArn(input.principalArn)) throw new Error("The trusted principal must be an IAM role ARN.")
  return input
}

function yamlActions(actions: readonly string[], indent: string): string {
  return actions.map((action) => `${indent}- ${action}`).join("\n")
}

/**
 * The CloudFormation template. The external id is the parameter's default, so a
 * quick-create link or a plain upload deploys the right trust without editing anything.
 */
export function awsCloudFormationTemplate(input: AwsArtifactInput): string {
  const { externalId, principalArn } = checked(input)
  const statements = POLICY.statements
    .map((statement) =>
      [
        `              # ${statement.purpose}`,
        `              - Sid: ${statement.sid}`,
        "                Effect: Allow",
        "                Action:",
        yamlActions(statement.actions, "                  "),
        statement.self_only
          ? `                Resource: !Sub arn:aws:iam::\${AWS::AccountId}:role${AWS_ROLE_PATH}${AWS_ROLE_NAME}`
          : '                Resource: "*"',
      ].join("\n")
    )
    .join("\n")

  return `AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Read-only role for the reporting agent. It can list resources and read
  CloudWatch metrics in this account. It cannot change anything, and it cannot
  read data: no S3 objects, no database contents, no secrets.

Parameters:
  ExternalId:
    Type: String
    Description: Issued by the reporting app for this connection. Do not change it.
    Default: ${externalId}

Resources:
  ReportingAgentReader:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${AWS_ROLE_NAME}
      Path: ${AWS_ROLE_PATH}
      MaxSessionDuration: ${POLICY.max_session_seconds}
      Description: Read-only access for the reporting agent
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Only the reporting agent's runtime, and only with this connection's external ID.
          - Effect: Allow
            Principal:
              AWS: ${principalArn}
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      Policies:
        - PolicyName: ${AWS_POLICY_NAME}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
${statements}

Outputs:
  RoleArn:
    Value: !GetAtt ReportingAgentReader.Arn
`
}

function permissionsJson(accountId: string): string {
  const document = {
    Version: "2012-10-17",
    Statement: POLICY.statements.map((statement) => ({
      Sid: statement.sid,
      Effect: "Allow",
      Action: statement.actions,
      Resource: statement.self_only ? readerRoleArn(accountId) : "*",
    })),
  }
  return JSON.stringify(document, null, 2)
}

function trustJson(principalArn: string, externalId: string): string {
  const document = {
    Version: "2012-10-17",
    Statement: [
      {
        Effect: "Allow",
        Principal: { AWS: principalArn },
        Action: "sts:AssumeRole",
        Condition: { StringEquals: { "sts:ExternalId": externalId } },
      },
    ],
  }
  return JSON.stringify(document, null, 2)
}

/**
 * The CLI script, for AWS CloudShell. Safe to run twice: on a second run it replaces the
 * role's trust and permissions rather than failing, which is also how a customer moves the
 * role to a new connector's external id.
 */
export function awsCliScript(input: AwsArtifactInput): string {
  const { accountId, externalId, principalArn } = checked(input)

  return `#!/usr/bin/env bash
# Creates the read-only role the reporting agent assumes in this AWS account.
# Run it in AWS CloudShell, signed in to account ${accountId} as someone allowed
# to create IAM roles. Running it again updates the role in place.
set -euo pipefail

ACCOUNT_ID="${accountId}"
ROLE_NAME="${AWS_ROLE_NAME}"

# 1. Stop if this terminal is signed in to a different account.
if [ "$(aws sts get-caller-identity --query Account --output text)" != "$ACCOUNT_ID" ]; then
  echo "This terminal is signed in to a different account. Expected $ACCOUNT_ID." >&2
  exit 1
fi

# 2. Who may assume the role: only the reporting agent, only with this connection's external ID.
cat > trust.json <<'EOF'
${trustJson(principalArn, externalId)}
EOF

# 3. What the role may do: list resources and read metrics. No writes, no data reads.
cat > permissions.json <<'EOF'
${permissionsJson(accountId)}
EOF

if aws iam get-role --role-name "$ROLE_NAME" >/dev/null 2>&1; then
  aws iam update-assume-role-policy --role-name "$ROLE_NAME" \\
    --policy-document file://trust.json
else
  aws iam create-role --role-name "$ROLE_NAME" --path ${AWS_ROLE_PATH} \\
    --max-session-duration ${POLICY.max_session_seconds} \\
    --description "Read-only access for the reporting agent" \\
    --assume-role-policy-document file://trust.json
fi
aws iam put-role-policy --role-name "$ROLE_NAME" \\
  --policy-name ${AWS_POLICY_NAME} --policy-document file://permissions.json

# 4. Done. Go back to the connection page and click Verify.
aws iam get-role --role-name "$ROLE_NAME" --query Role.Arn --output text
`
}

export type AwsOnboardingArtifacts = {
  readonly roleArn: string
  readonly cloudFormation: string
  readonly cliScript: string
}

export function awsOnboardingArtifacts(input: AwsArtifactInput): AwsOnboardingArtifacts {
  return {
    roleArn: readerRoleArn(input.accountId),
    cloudFormation: awsCloudFormationTemplate(input),
    cliScript: awsCliScript(input),
  }
}
